// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:02af493f-c48d-4e2f-bc1c-8b8e55ef4dde",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rJ81jFmOC",
    "aws_user_pools_web_client_id": "v15lb0je1rphd38bssfq54ldq",
    "aws_mobile_analytics_app_id": "19dde061320346a89b97eef61c1acd49",
    "aws_mobile_analytics_app_region": "eu-west-1",
    "aws_content_delivery_bucket": "amplifyjsapp-20190211112407-hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://amplifyjsapp-20190211112407-hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
